/*
 * This source file was generated by the Gradle 'init' task
 */
package com.andihasan7.lib.nizhamul.qomaroin

import com.andihasan7.lib.nizhamul.qomaroin.gerhanabulan.GerhanaBulan
import com.andihasan7.lib.nizhamul.qomaroin.gerhanamatahari.GerhanaMatahari
import com.andihasan7.lib.nizhamul.qomaroin.util.round

fun main() {
    
    
    val gb = GerhanaBulan(
    	-7.231111111111,
        106.515555555556,
        333.0, // elevation 
        7.0, // timeZone
        5, // bulan hijri
        1439, // tahun hijri
        31, // tgl miladi
        1, // bulan miladi
        2018, // tahun miladi
        14, // T0
        1, // nau'
        2458150.1,
        70.5, // deltaT
        0.2224, // x0
        0.5742, // x1
        -0.3517, // y0
        -0.1054, // y1
        1.5741, // l10
        -0.0003, // l11
        1.0331, // l20
        -0.0003, // l21
        0.4802, // l30
        -0.0002, // l31
        0.2764, // sdb0
        -0.0001, // sdb1
        206.4090, // m0
        14.3989, // m1
        16.9335, // dm0
        -0.1178, // dm1
        134.3285, // ra0
        0.6427, // ra1
        1.0145000, // hp0
        -0.0003000 // hp1
    )
    
    val jenisGB = gb.jenisGB
    val tahunGB = gb.tahunGB
    val bulanStringGB = gb.bulanStringGB
    val tanggalGB = gb.tanggalGB
    val hariStringGB = gb.hariStringGB
    val pasaranStringGB = gb.pasaranStringGB
    
    val awalPenumbraUT = gb.awalPenumbraUTHMS
    val awalPenumbraLokal = gb.awalPenumbraLokalHMS
    val awalUmbraUT = gb.awalUmbraUTHMS
    val awalUmbraLokal = gb.awalUmbraLocalHMS
    val awalTotalUT = gb.awalTotalUTHMS
    val awalTotalLokal = gb.awalTotalLocalHMS
    val puncakUT = gb.puncakGerhanaUTHMS
    val puncakLokal = gb.puncakGerhanaLocalHMS
    val akhirTotalUT = gb.akhirTotalUTHMS
    val akhirTotalLokal = gb.akhirTotalLocalHMS
    val akhirUmbraUT = gb.akhirUmbraUTHMS
    val akhirUmbraLokal = gb.akhirUmbraLocalHMS
    val akhirPenumbraUT = gb.akhirPenumbraUTHMS
    val akhirPenumbraLokal = gb.akhirPenumbraLocalHMS
    
    // alt & az awal penumbra
    val tinggiHakikiAwalPenumbra = gb.tinggiHakikiAwalPenumbra
    val tinggiMariAwalPenumbra = gb.tinggiMariAwalPenumbra
    val azimuthAwalPenumbra = gb.azimuthAwalPenumbraDegree
    // alt & az awal umbra
    val tinggiHakikiAwalUmbra = gb.tinggiHakikiAwalUmbra
    val tinggiMariAwalUmbra = gb.tinggiMariAwalUmbra
    val azimuthAwalUmbra = gb.azimuthAwalUmbraDegree
    // alt & az awal total
    val tinggiHakikiAwalTotal = gb.tinggiHakikiAwalTotal
    val tinggiMariAwalTotal = gb.tinggiMariAwalTotal
    val azimuthAwalTotal = gb.azimuthAwalTotalDegree
    // alt & az puncak gerhana
    val tinggiHakikiPuncakGerhana = gb.tinggiHakikiPuncakGerhana
    val tinggiMariPuncakGerhana = gb.tinggiMariPuncakGerhana
    val azimuthPuncakGerhana = gb.azimuthPuncakGerhanaDegree
    // alt & az akhir total
    val tinggiHakikiAkhirTotal = gb.tinggiHakikiAkhirTotal
    val tinggiMariAkhirTotal = gb.tinggiMariAkhirTotal
    val azimuthAkhirTotal = gb.azimuthAkhirTotalDegree
    // alt & az akhir umbra
    val tinggiHakikiAkhirUmbra = gb.tinggiHakikiAkhirUmbra
    val tinggiMariAkhirUmbra = gb.tinggiMariAkhirUmbra
    val azimuthAkhirUmbra = gb.azimuthAkhirUmbraDegree
    // alt & az akhir penumbra
    val tinggiHakikiAkhirPenumbra = gb.tinggiHakikiAkhirPenumbra
    val tinggiMariAkhirPenumbra = gb.tinggiMariAkhirPenumbra
    val azimuthAkhirPenumbra = gb.azimuthAkhirPenumbraDegree
    
    val magPenumb = gb.magPenumbraRound
    val magUmbra = gb.magUmbraRound
    
    val durasiPenumbra = gb.durasiPenumbraHMS
    val durasiUmbra = gb.durasiUmbraHMS
    val durasiTotal = gb.durasiTotalHMS
    
    val radiusPenumbra = gb.radiusPenumbraRound
    val radiusUmbra = gb.radiusUmbraRound
    
    println(" ")
    println("Date : $hariStringGB $pasaranStringGB, $tanggalGB $bulanStringGB $tahunGB")
    println(" ")
    println("Jenis Gerhana     : $jenisGB")
    println(" ")
    println("Awal Penumbra UT  : $awalPenumbraUT")
    println("Awal Umbra UT     : $awalUmbraUT")
    println("Awal Total UT     : $awalTotalUT")
    println("Puncak Gerhana UT : $puncakUT")
    println("Akhir Total UT    : $akhirTotalUT")
    println("Akhir Umbra UT    : $akhirUmbraUT")
    println("Akhir Penumbra UT : $akhirPenumbraUT")
    println(" ")
    println("Awal Penumbra WD  : $awalPenumbraLokal")
    println("Awal Umbra WD     : $awalUmbraLokal")
    println("Awal Total WD     : $awalTotalLokal")
    println("Puncak Gerhana WD : $puncakLokal")
    println("Akhir Total WD    : $akhirTotalLokal")
    println("Akhir Umbra WD    : $akhirUmbraLokal")
    println("Akhir Penumbra WD : $akhirPenumbraLokal")
    println(" ")
    println("Alt Hakiki Awal Penumbra : $tinggiHakikiAwalPenumbra")
    println("Alt Mar'i Awal Penumbra  : $tinggiMariAwalPenumbra")
    println("Azimuth Awal Penumbra    : $azimuthAwalPenumbra")
    println(" ")
    println("Alt Hakiki Awal Umbra    : $tinggiHakikiAwalUmbra")
    println("Alt Mar'i Awal Umbra     : $tinggiMariAwalUmbra")
    println("Azimuth Awal Umbra       : $azimuthAwalUmbra")
    println(" ")
    println("Alt Hakiki Awal Umbra    : $tinggiHakikiAwalTotal")
    println("Alt Mar'i Awal Umbra     : $tinggiMariAwalTotal")
    println("Azimuth Awal Total       : $azimuthAwalTotal")
    println(" ")
    println("Alt Hakiki Awal Puncak   : $tinggiHakikiPuncakGerhana")
    println("Alt Mar'i Awal Puncak    : $tinggiMariPuncakGerhana")
    println("Azimuth Puncak Gerhana   : $azimuthPuncakGerhana")
    println(" ")
    println("Alt Hakiki Akhir Total   : $tinggiHakikiAkhirTotal")
    println("Alt Mar'i Akhir Total    : $tinggiMariAkhirTotal")
    println("Azimuth Akhir Total      : $azimuthAkhirTotal")
    println(" ")
    println("Alt Hakiki Akhir Umbra   : $tinggiHakikiAkhirUmbra")
    println("Alt Mar'i Akhir Umbra    : $tinggiMariAkhirUmbra")
    println("Azimuth Akhir Umbra      : $azimuthAkhirUmbra")
    println(" ")
    println("Alt Hakiki Akhir Penumbra: $tinggiHakikiAkhirPenumbra")
    println("Alt Mar'i Akhir Penumbra : $tinggiMariAkhirPenumbra")
    println("Azimuth Akhir Penumbra   : $azimuthAkhirPenumbra")
    println(" ")
    println("Mag Penumbra    : $magPenumb")
    println("Mag Umbra       : $magUmbra")
    println("Durasi Penumbra : $durasiPenumbra")
    println("Durasi Umbra    : $durasiUmbra")
    println("Durasi Total    : $durasiTotal")
    println("Radius Penumbra : $radiusPenumbra")
    println("Radius Umbra    : $radiusUmbra")
    println(" ")
    
    /*
    val t = gb.t
    val tg = gb.tgHMS
    val s = gb.s
    val x = gb.x
    val y = gb.y
    val z = gb.z
    val k = gb.k
    
    val t1 = gb.t1
    val t2 = gb.t2
    val t3 = gb.t3
    
    val sdb = gb.sdb
    
    val tc = gb.tc
    val dec = gb.dec
    val h = gb.h
    val p = gb.p
    val hh = gb.hh
    val rf = gb.rf
    val h_h = gb.h_h
    val xmax = gb.xMax
    val ymax = gb.yMax
    val azmax = gb.azMax
    val azimuthPuncakGerhana = gb.azimuthPuncakGerhana
    
    val tPen1 = gb.tPen1
    val decPen1 = gb.decPen1
    val hPen1 = gb.hPen1
    val pPen1 = gb.pPen1
    val hhPen1 = gb.hhPen1
    val rfPen1 = gb.rfPen1
    val h_hPen1 = gb.h_hPen1
    val xPenum = gb.xPenum
    val yPenum = gb.yPenum
    val azPenum = gb.azPenum
    val azimuthAwalPenumbra = gb.azimuthAwalPenumbra
    
    val tu1 = gb.tu1
    val decTu1 = gb.decTu1
    val hu1 = gb.hu1
    val pu1 = gb.pu1
    val hhU1 = gb.hhU1
    val rfU1 = gb.rfU1
    val h_hU1 = gb.h_hU1
    val xUmbra = gb.xUmbra
    val yUmbra = gb.yUmbra
    val azUmbra = gb.azUmbra
    val azimuthAwalUmbra = gb.azimuthAwalUmbra
    
    
    val tu2 = gb.tu2
    val decTu2 = gb.decTu2
    val hu2 = gb.hu2
    val pu2 = gb.pu2
    val hhU2 = gb.hhU2
    val rfU2 = gb.rfU2
    val h_hU2 = gb.h_hU2
    val xU2 = gb.xU2
    val yU2 = gb.yU2
    val azU2 = gb.azU2
    val azimuthAwalTotal = gb.azimuthAwalTotal
    
    val tu3 = gb.tu3
    val decTu3 = gb.decTu3
    val hu3 = gb.hu3
    val pu3 = gb.pu3
    val hhU3 = gb.hhU3
    val rfU3 = gb.rfU3
    val h_hU3 = gb.h_hU3
    val xU3 = gb.xU3
    val yU3 = gb.yU3
    val azU3 = gb.azU3
    val azimuthAkhirTotal = gb.azimuthAkhirTotal
    
    val tu4 = gb.tu4
    val decTu4 = gb.decTu4
    val hu4 = gb.hu4
    val pu4 = gb.pu4
    val hhU4 = gb.hhU4
    val rfU4 = gb.rfU4
    val h_hU4 = gb.h_hU4
    val xU4 = gb.xU4
    val yU4 = gb.yU4
    val azU4 = gb.azU4
    val azimuthAkhirUmbra = gb.azimuthAkhirUmbra
    
    val tPen4 = gb.tPen4
    val decPen4 = gb.decPen4
    val hPen4 = gb.hPen4
    val pPen4 = gb.pPen4
    val hhPen4 = gb.hhPen4
    val rfPen4 = gb.rfPen4
    val h_hPen4 = gb.h_hPen4
    val xPen4 = gb.xPen4
    val yPen4 = gb.yPen4
    val azPen4 = gb.azPen4
    val azimuthAkhirPenumbra = gb.azimuthAkhirPenumbra
    
    println("t : $t")
    println("tg : $tg")
    println("s : $s")
    println("x : $x")
    println("y : $y")
    println("z : $z")
    println("k : $k")
    println("t1 : $t1")
    println("t2 : $t2")
    println("t3 : $t3")
    println("sdb : $sdb")
    println("")
    println("tc : $tc")
    println("dec : $dec")
    println("h : $h")
    println("p : $p")
    println("hh : $hh")
    println("rf : $rf"))
    println("h_h : $h_h")
    println("x : $xmax")
    println("y : $ymax")
    println("azmax : $azmax")
    println("")
    println("tPen1 : $tPen1")
    println("decPen1 : $decPen1")
    println("hPen1 : $hPen1")
    println("pPen1 : $pPen1")
    println("hhPen1 : $hhPen1")
    println("rf p1 : $rfPen1")
    println("h_hPen1 : $h_hPen1")
    println("x penum : $xPenum")
    println("y penum : $yPenum")
    println("az penum : $azPenum")
    println(" ")
    println("tu1 : $tu1")
    println("decTu1 : $decTu1")
    println("hu1 : $hu1")
    println("pu1 : $pu1")
    println("hhU1 : $hhU1")
    println("rf u1 : $rfU1")
    println("h_hU1 : $h_hU1")
    println("x umbra : $xUmbra")
    println("y umbra : $yUmbra")
    println("az umbra : $azUmbra")
    println("")
    println("tu2 : $tu2")
    println("decTu2 : $decTu2")
    println("hu2 : $hu2")
    println("pu2 : $pu2")
    println("hhU2 : $hhU2")
    println("rf u2 : $rfU2")
    println("h_hU2 : $h_hU2")
    println("x awal t: $xU2")
    println("y awal t : $yU2")
    println("az awal total : $azU2")
    println("")
    println("tu3 : $tu3")
    println("decTu3 : $decTu3")
    println("hu3 : $hu3")
    println("pu3 : $pu3")
    println("hhU3 : $hhU3")
    println("rf u3 : $rfU3")
    println("h_hU3 : $h_hU3")
    println("x akhir t: $xU3")
    println("y akhir t : $yU3")
    println("az akhir total : $azU3")
    println("")
    println("tu4 : $tu4")
    println("decTu4 : $decTu4")
    println("hu4 : $hu4")
    println("pu4 : $pu4")
    println("hhU4 : $hhU4")
    println("rf u4 : $rfU4")
    println("h_hU4 : $h_hU4")
    println("x akhir umbra: $xU4")
    println("y akhir umbra : $yU4")
    println("az akhir umbra : $azU4")
    println("")
    println("tPen4 : $tPen4")
    println("decPen4 : $decPen4")
    println("hPen4 : $hPen4")
    println("pPen4 : $pPen4")
    println("hhPen4 : $hhPen4")
    println("rf p4 : $rfPen4")
    println("h_hPen4 : $h_hPen4")
    println("x akhir penum : $xPen4")
    println("y akhir penum : $yPen4")
    println("az akhir penum : $azPen4")
    */
    
    // gerhana matahari nidzomul qomaroin
    val nq =
        GerhanaMatahari(
            -2.856944444444, // lintang
            108.297222222222, // bujur
            2.0, // TT
            7.0, // TZ
            5, // bulan hijri
            1437, // tahun hijri
            9, // tanggal miladi
            3, // bulan miladi
            2016, // tahun miladi
            2, // TO/TD
            1, // nau'
            2457456.5, // JD
            69.6, // deltaT
            -0.06252, // X0
            0.55028, // X1
            0.0, // X2
            0.25384, // Y0
            0.17212, // Y1
            0.00002, // Y2
            -4.37971, // d0
            0.015886, // d1
            0.000001, // d2
            207.37261, // M0
            15.00397, // M1
            0.53889, // L1 0
            -0.00007, // L1 1
            -0.00001, // L1 2
            -0.00723, // L2 0
            -0.00007, // L2 1
            -0.00001, // L2 2
            0.00471, // tanF 1
            0.00469 // tanF 2
        )

	val jenisGerhana = nq.jenisGerhana
    val awalGerhanaHMS = nq.awalGerhanaHMS
    val awalTotalHMS = nq.awalTotalHMS
    val puncakGerhanaHMS = nq.puncakGerhanaHMS
    val akhirTotalHMS = nq.akhirTotalHMS
    val akhirGerhanaHMS = nq.akhirGerhanaHMS
    val alt_u1 = nq.tinggiAwalGerhanaDegree
    val alt_u2 = nq.tinggiAwalTotalDegree
    val alt_Max = nq.tinggiPuncakDegree
    val alt_u3 = nq.tinggiAkhirTotalDegree
    val alt_u4 = nq.tinggiAkhirGerhanaDegree
    val azU1 = nq.azimuthAwalGerhanaDegree
    val azU2 = nq.azimuthAwalTotalDegree
    val azMax = nq.azimuthPuncakDegree
    val azU3 = nq.azimuthAkhirTotalDegree
    val azU4 = nq.azimuthAkhirGerhanaDegree
    val totalDurasiGB = nq.totalDurasiGMHMS
    val durasiTotalGB = nq.durasiTotalGMHMS
    // val magni = nq.Mag.round(3)
    val Mag = nq.magnitude.round(3)
    val Obsk = nq.Obsk
    
    
    val tahun = nq.tahun
    val bulanString = nq.bulanString
    val tanggal = nq.tanggal
    val hariString = nq.hariString
    val pasaranString = nq.pasaranString
    
    
    println(" ")
    println("Date : $hariString $pasaranString, $tanggal $bulanString $tahun")
    println(" ")
    println("Jenis Gerhana : $jenisGerhana")
    println(" ")
    println("Awal Gerhana       : $awalGerhanaHMS")
    println("Awal Total         : $awalTotalHMS")
    println("Puncak Gerhana     : $puncakGerhanaHMS")
    println("Akhir Total        : $akhirTotalHMS")
    println("Akhir Gerhana      : $akhirGerhanaHMS")
    println(" ")
    println("Tinggi Awal Gerhana  : $alt_u1")
    println("Tinggi Awal Total    : $alt_u2")
    println("Tinggi Puncak        : $alt_Max")
    println("Tinggi Akhir Total   : $alt_u3")
    println("Tinggi Akhir Gerhana : $alt_u4")
    println(" ")
    println("Azimuth Awal Gerhana : $azU1")
    println("Azimuth Awal Total   : $azU2")
    println("Azimuth Puncak       : $azMax")
    println("Azimuth Akhir Total  : $azU3")
    println("Azimuth Akhir Gerhana: $azU4")
    println(" ")
    println("Magnitude            : $Mag")
    //println("Magnitude max eclp : $magni")
    println("Total Durasi         : $totalDurasiGB")
    println("Durasi Total/Cincin  : $durasiTotalGB")
    println("Obskurasi            : $Obsk %")
    
    /*
    
    val cjd = nq.cjd
    val zh = nq.zh
    val ff = nq.ff
    val alpha = nq.alpha
    val ac = nq.Ac
    val bc = nq.Bc
    val cC = nq.cC
    val Dc = nq.Dc
    val Ec = nq.Ec
    val hari = nq.hari
    val pasaran = nq.pasaran
    
    val P1 = nq.P1
    val P2 = nq.P2
    val P3 = nq.P3
    val P4 = nq.P4
    val P5 = nq.P5
    val t = nq.t
    val K = nq.K
    val m = nq.m
    val lL = nq.lL
    val qQ = nq.qQ
    val e = nq.e
    val z = nq.z
    val Tau = nq.Tau
    
    val rR = nq.rR
    val sS = nq.sS
    val y = nq.y
    val zZ = nq.zZ
    val a = nq.a
    val b = nq.b
    val BB = nq.BB
    val CC = nq.CC
    
    
    val w = nq.w
    val d = nq.d
    
    
    val pwAwal = nq.pwAwal
    val pwAkhir = nq.pwAkhir
    
    val Pe = nq.Pe
    val Pf = nq.Pf
    
    val t2 = nq.t2
    
    
    val Pg = nq.Pg
    val Ph = nq.Ph
    
    val t3 = nq.t3
    
    
    val tU1 = nq.tU1
    val dU1 = nq.dU1
    val raU1 = nq.raU1
    val hau1 = nq.hau1
    
    val xU1 = nq.xU1
    val yU1 = nq.yU1
    val aU1 = nq.aU1
    
    
    val tU2 = nq.tU2
    val dU2 = nq.dU2
    val raU2 = nq.raU2
    val hau2 = nq.hau2
    
    val xU2 = nq.xU2
    val yU2 = nq.yU2
    val aU2 = nq.aU2
    
    
    val tMax = nq.tMax
    val dMax = nq.dMax
    val raMax = nq.raMax
    val hauMax = nq.hauMax
    
    val xMax = nq.xMax
    val yMax = nq.yMax
    val aMax = nq.aMax
    
    
    val tU3 = nq.tU3
    val dU3 = nq.dU3
    val raU3 = nq.raU3
    val hau3 = nq.hau3
    
    val xU3 = nq.xU3
    val yU3 = nq.yU3
    val aU3 = nq.aU3
    
    
    val tU4 = nq.tU4
    val dU4 = nq.dU4
    val raU4 = nq.raU4
    val hau4 = nq.hau4
    
    val xU4 = nq.xU4
    val yU4 = nq.yU4
    val aU4 = nq.aU4
    
    println("cjd : $cjd")
    println("zh : $zh")
    println("ff : $ff")
    println("alpha : $alpha")
    println("ac : $ac")
    println("bc : $bc")
    println("cC : $cC")
    println("Dc : $Dc")
    println("Ec : $Ec")
    println("tanggal : $tanggal")
    println("hari : $hari")
    println("hari : $hariString")
    println("pasaran : $pasaran")
    println("pasaran : $pasaranString")
    
	println("P1 : $P1")
    println("P2 : $P2")
    println("P3 : $P3")
    println("P4 : $P4")
    println("P5 : $P5")
    println("t = $t")
    println("puncak gerhana : $K")
    
    println("m : $m")
    println("L' : $lL")
    println("Q' : $qQ")
    println("e : $e")
    println("z : $z")
    println("Tau : $Tau")
    println("Mag : $Mag")
    println("r' : $rR")
    println("s' : $sS")
    println("y : $y")
    println("zZ : $zZ")
    println("a : $a")
    println("b : $b")
    println("BB : $BB")
    println("CC : $CC")
    println("Obsk : $Obsk")
    println("jenis : $jenisGerhana")
    println("w : $w")
    println("d : $d")
    println("Pe : $Pe")
    println("Pf : $Pf")
    println("t2 : $t2")
    println("Pg : $Pg")
    println("Ph : $Ph")
    println("t3 : $t3")
    println(" ")
    println("tU1 : $tU1")
    println("dU1 : $dU1")
    println("raU1 : $raU1")
    println("hau1 : $hau1")
    println("")
    println("xU1 : $xU1")
    println("yU1 : $yU1")
    println("aU1 : $aU1")
    
    println("tU2 : $tU2")
    println("dU2 : $dU2")
    println("raU2 : $raU2")
    println("hau2 : $hau2")
    
    println("xU2 : $xU2")
    println("yU2 : $yU2")
    println("aU2 : $aU2")
    
    println(" ")
    println("tMax : $tMax")
    println("dMax : $dMax")
    println("raMax : $raMax")
    println("hauMax : $hauMax")
    
    println("xMax : $xMax")
    println("yMax : $yMax")
    println("aMax : $aMax")
    
    println(" ")
    println("tU3 : $tU3")
    println("dU3 : $dU3")
    println("raU3 : $raU3")
    println("hau3 : $hau3")
    
    println("xU3 : $xU3")
    println("yU3 : $yU3")
    println("aU3 : $aU3")
    
    println(" ")
    println("tU4 : $tU4")
    println("dU4 : $dU4")
    println("raU4 : $raU4")
    println("hau4 : $hau4")
    
    println("xU4 : $xU4")
    println("yU4 : $yU4")
    println("aU4 : $aU4")
    */
}
